name: Web API Deploy Pipeline
on: 
  push:
    paths:
      - '.github/workflows/**'
      - 'cicd-section/api/**'
  
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: my-app-cluster
  ECS_SERVICE: my-app-api
  ECS_TASK_DEFINITION_API: cicd-section/.aws/task-def-api.json
  ECR_REPOSITORY: my-app-api

permissions:
  id-token: write
  contents: read

jobs:
# Test/Build
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd-section-api
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      - name: Run Test execution
          run: |
            docker image build -t temp_api_image:latest .
      
      - name: Configure AWS Credentials OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}} #後で確認予定

      - name: Login to ECR
        id: lofin-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTORY: ${{ steps.login-ecr.outputs.repository}} 
          # Login to ECRの結果の中の'repository'の値を参照する
        run: |
          docker image tag temp_api_image:latest $ECR_REGISTORY/$ECR_REPOSITORY:${{ github.sha }}
        # docker image tag temp_api_image:latest {アカウントID}.dkr.ecr.ap-northeast-1.amazonaws.com/my-app-api:{sha}
          docker image push $ECR_REGISTORY/$ECR_REPOSITORY:${{ github.sha }}

# Deploy
